title: 2020 in Buffalo News Front Pages # 
logo:
description: > # your text below (remove <br> elements if you don't need line breaks)
  vicky johnson-dahl<br>
  cartographer, dc
  <br>  
  <br>
  <a href="https://www.twitter.com/hurricanevicky/">twitter</a> // <a href="mailto:victoria.johnson@gmail.com?subject=go bills">email</a> 
  <br>
  <br>
 
  
theme: jekyll-theme-minimal
google_analytics: G-LRMZJ6X72H # your Google Analytics tracking ID here
